### ISSUE TITLE
Fails to parse dates that include "st", "rd", "th", "nd"

### ISSUE THREAD

**Issue by djwillcaine** [tokenmill/timewords#13]
When passing in a string that uses "st", "rd", "th", or "nd" after the day, the returned result is always the 1st of the month.

```clojure
(parse "24th November")

;; Expected result
#inst "2021-11-24T00:00:00.000-00:00"

;; Actual result
#inst "2021-11-01T00:00:00.000-00:00"
```

Work around is fairly simple, by removing any matches for those strings, but it would be nice to implement this directly into the library. Will submit a PR later.

**Comment by zmedelis** [comment]
@djwillcaine this is a good suggestion, I can implement that or are you planning to do a PR?
